FROM centos:7

RUN yum update -y && yum install -y \
	epel-release \
	openssl-devel \
	libcurl \
	libcurl-devel \
	cairo-devel \
	libxml2-devel \
	udunits2-devel \
	cronie && \
	yum install -y R && \
	R -e 'install.packages(c("bit64","ggplot2","plotly","shiny","shinydashboard","shinyWidgets","data.table","readr","devtools","shinycssloaders","DT"),repos="https://mirror.ibcp.fr/pub/CRAN/");'

RUN mkdir /usr/local/src/app

RUN R -e 'install.packages("reactlog",repos="https://mirror.ibcp.fr/pub/CRAN/");'

COPY . /usr/local/src/app
WORKDIR /usr/local/src/app
ENTRYPOINT ["Rscript","boardion_app.R"]

