FROM centos:7

RUN yum update -y && yum install -y \
	epel-release \
	openssl-devel \
	libcurl \
	libcurl-devel \
	cairo-devel \
	libxml2-devel \
	udunits2-devel \
	cronie && \
	yum install -y R && \
	R -e 'install.packages(c("bit64","ggplot2","plotly","shiny","shinydashboard","shinyWidgets","data.table","readr","devtools","shinycssloaders","DT"),repos="https://mirror.ibcp.fr/pub/CRAN/");' 

RUN yum install -y htop

COPY ./app /usr/home/root/app
COPY ./demo /usr/home/root/demo

#RUN crontab /usr/home/root/demo/demo-crontab && \
RUN mkdir /usr/home/root/demo/data /usr/home/root/demo/stat /usr/home/root/demo/logs

ENTRYPOINT ["/usr/home/root/demo/demo.sh"]

