FROM centos:7

RUN yum update -y && yum install -y \
	epel-release \
	openssl-devel \
	libcurl \
	libcurl-devel \
	cairo-devel \
	libxml2-devel \
	udunits2-devel \
	cronie && \
	yum install -y R && \
	R -e 'install.packages(c("bit64","ggplot2","plotly","shiny","shinydashboard","shinyWidgets","data.table","readr","devtools","shinycssloaders","DT"),repos="https://mirror.ibcp.fr/pub/CRAN/");' 

RUN yum install -y htop

COPY ./ /usr/local/src/

RUN mkdir /usr/local/src/demo/data /usr/local/src/demo/stat /usr/local/src/demo/logs

ENTRYPOINT ["/usr/local/src/demo/demo.sh"]

